### ISSUE TITLE
The dimension of SHOT descriptor

### ISSUE THREAD

**Issue by dongliangcao** [uhlmanngroup/pyshot#2]
Dear author,

Thanks for your work. I have encountered a problem when I use the library to compute SHOT descriptor. I notice in the comment it is mentioned that the dimension of the SHOT descriptor is equal to 16 * (n_bins + 1) * (double_volumes + 1). But when I set n_bins=11 and double_volumes=True. I always get a dimension with 128 rather than 352 as expected. Do you know why it would be the case.

Thanks in advance.

Best regards,
Dongliang

**Comment by dongliangcao** [comment]
> Dear author,
> 
> Thanks for your work. I have encountered a problem when I use the library to compute SHOT descriptor. I notice in the comment it is mentioned that the dimension of the SHOT descriptor is equal to 16 * (n_bins + 1) * (double_volumes + 1). But when I set n_bins=11 and double_volumes=True. I always get a dimension with 128 rather than 352 as expected. Do you know why it would be the case.
> 
> Thanks in advance.
> 
> Best regards, Dongliang

I check the code and I think the potential reason is that the ordering of the min_neighbors and n_bins is not consistent in head file of c++ and in the definition in python.

**Comment by jjerphan** [comment]
Hi @dongliangcao.

Thank for your interest!
Can you [craft a minimal bug report](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)?

This way I could inspect the problem and solve it.

Best,
Julien.

**Comment by dongliangcao** [comment]
> Hi @dongliangcao.
> 
> Thank for your interest! Can you [craft a minimal bug report](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)?
> 
> This way I could inspect the problem and solve it.
> 
> Best, Julien.

RADIUS = 0.09
NUM_BINS = 10
MIN_NEIGHBORS = 3

# random generate vertices and faces
verts = np.random.rand(5000, 3) # [5000, 3]
faces = np.random.choice(5000, size=(10000, 3), replace=True) # [10000, 3]

shot_features = get_descriptors(verts, faces,
                                            radius=RADIUS, local_rf_radius=RADIUS,
                                            min_neighbors=NUM_BINS,
                                            n_bins=MIN_NEIGHBORS,
                                            double_volumes_sectors=True,
                                            use_interpolation=True,
                                            use_normalization=True).reshape(-1, 352)
the code above works as you can see to exchange the value of min_neighors and n_bins.
